//package org.example.model;
//
//import jakarta.persistence.*;//jpa //provides the ORM functionality tables->objects
///**
// * Represents a Category entity mapped to the "categories" database table.
// *
// * This class uses JPA annotations to define the ORM mapping between the class and the database.
// * Each instance corresponds to a row in the "categories" table.
// */
//@Entity//table
//@Table(name="categories")
//public class Category {
//    /** The primary key for the category, auto-generated by the database. */
//    @Id//primary key
//    @GeneratedValue(strategy= GenerationType.IDENTITY)//primary key is auto-incremented
//    /** The name of the category. */
//    @Column
//
//    private int id;
//    @Column
//    private String name;
//    /**
//     * Default no-argument constructor required by JPA.
//     */
//    public Category(){}
//    /**
//     * Constructs a Category with the specified id and name.
//     *
//     * @param id the unique identifier of the category
//     * @param name the name of the category
//     */
//    public Category(int id, String name)
//    {
//        this.id=id;
//        this.name=name;
//    }
//    /**
//     * Returns the category's id.
//     *
//     * @return the id of the category
//     */
//    public int getID()
//    {
//        return(this.id);
//    }
//    /**
//     * Returns the category's name.
//     *
//     * @return the name of the category
//     */
//    public String getName()
//    {
//        return(this.name);
//    }
//    /**
//     * Sets the category's id.
//     *
//     * @param id the new id of the category
//     */
//    public void setID(int id)
//    {
//        this.id=id;
//    }
//    /**
//     * Sets the category's name.
//     *
//     * @param name the new name of the category
//     */
//    public void setName(String name)
//    {
//        this.name=name;
//    }
//
//}
package org.example.model;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;

import java.util.Set;

@Entity
@Table(name="categories")
public class Category {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private int id;

    @Column
    private String name;

    @OneToMany(mappedBy = "category") // 'category' is the field in the Product class
    @JsonManagedReference
    private Set<Product> products;

    // Default no-argument constructor required by JPA
    public Category() {}

    // Constructor
    public Category(String name) {
        this.name = name;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<Product> getProducts() {
        return products;
    }

    public void setProducts(Set<Product> products) {
        this.products = products;
    }
}
